# Generated by Django 4.2.2 on 2023-06-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "no_of_guests",
                    models.SmallIntegerField(verbose_name="Number of guests"),
                ),
                ("booking_date", models.DateTimeField(verbose_name="Booking date")),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Dish Name")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Dish Price"
                    ),
                ),
                ("inventory", models.SmallIntegerField(verbose_name="Dish Inventory")),
            ],
        ),
    ]
